# general settings
name: 2_SCGLAGAN_L_x4_Flickr1024
model_type: StereoSRGANModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 10

find_unused_parameters: true

# dataset and data loader settings
datasets:
  train:
    name: Flickr1024-sr-train
    type: PairedStereoImageDataset
    dataroot_gt: /home/iv/Annotation/ZJJ/datasets/Ntire2023/Track1&Track2_V2/HR_patch
    dataroot_lq: /home/iv/Annotation/ZJJ/datasets/Ntire2023/Track1&Track2_V2/LR_patch
    io_backend:
        type: disk

    gt_size_h: 96
    gt_size_w: 304
    use_hflip: true
    use_vflip: true
    use_rot: false
    flip_RGB: true

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Flickr1024-sr-val
    type: PairedStereoImageDataset

    dataroot_gt: /home/iv/Annotation/ZJJ/datasets/Ntire2023/Flickr1024/Validation
    dataroot_lq: /home/iv/Annotation/ZJJ/datasets/Ntire2023/Flickr1024/val_BIX4
    io_backend:
      type: disk

    batch_size_per_gpu: 1

# network structures
network_g:
  type: SCGLANet
  up_scale: 4
  width: 128
  num_blks: [16,16,32,32,32]
  drop_path_rate: 0.2
  train_size: [1, 6, 30, 90]
  drop_out_rate: 0.
  temperature: 2

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 6
  num_feat: 64
  skip_connection: True
# path
path:
  pretrain_network_g: ./experiments/pretrained_models/scglanet_x4_Track1.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
    ema_decay: 0
    optim_g:
      type: Adam
      lr: !!float 1e-4
      weight_decay: 0
      betas: [0.9, 0.99]
    optim_d:
      type: Adam
      lr: !!float 1e-4
      weight_decay: 0
      betas: [0.9, 0.99]

    scheduler:
      type: MultiStepLR
      milestones: [400000]
      gamma: 0.5

    total_iter: 400000
    warmup_iter: -1  # no warm up

    # losses
    pixel_opt:
      type: L1Loss
      loss_weight: 0.1
      reduction: mean
    lpips_opt:
      type: LPIPSLoss
      net_type: vgg
      use_rangenorm: true
      perceptual_weight: !!float 1.0
    # gan loss
    gan_opt:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: !!float 0.1
    #  ldl_opt:
    #    type: L1Loss

    net_d_iters: 1
    net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 2500
  save_img: true
  max_val: ~
  pbar: true
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_skimage_ssim
    lpips:
      type: cal_lpips
#      crop_border: 0
#      test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
